### ISSUE TITLE
Can you provide Db.roo in any open format?

### ISSUE THREAD

**Issue by nerixim** [Jooss287/RooSim#52]
Hi, thanks for your work.
I'm trying to do something similar to your work for Web, but I'm using Mac and I'm not familiar C# development.
I tried to build your project with Visual Studio as per instructions but I have some runtime errors I cannot get through.
Can you help with reading your db.roo file? Maybe I can have text (json?) or sqlite version of it?

**Comment by Jooss287** [comment]
Hi, thank you for your interest in my project.
It has been over 9 months since I quit and I have already deleted the database and do not have it. Sorry for not giving you a good answer.
I hope your project goes well.
